# Generated by Django 4.0.6 on 2022-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('Rname', models.CharField(max_length=40)),
                ('Remail', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Rnum', models.IntegerField(verbose_name=10)),
                ('password', models.CharField(max_length=10)),
                ('Rcpass', models.CharField(max_length=10)),
                ('Rcity', models.CharField(max_length=40)),
                ('Redu', models.CharField(max_length=50)),
                ('Raim', models.CharField(max_length=30)),
                ('Rhob', models.CharField(max_length=30)),
            ],
        ),
    ]
